FROM codigobicentenario/elixir:ubuntu

LABEL maintainer="raulumb@gmail.com"

RUN mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez

VOLUME /app/src/deps
VOLUME /app/src/_build
